#!/bin/bash

readonly ROOT="$(cd "$(dirname $0)" && pwd)"

for t in ${ROOT}/*_test.py; do
  python "$t" &> /dev/null
  if [[ $? != 0 ]] ; then
    echo "Tests for $t failed. Run 'python $t'."
    exit 1
  fi
done

echo "All tests passed."
exit 0
